/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * URLATE 백엔드 서버를 구동하기 위한 설정입니다.
 */
export interface URLATEConfig {
  /**
   * JSON 스키마 지정입니다.
   */
  $schema: string;
  project: Project;
  database: Database;
  redis: Redis;
  session: Session;
  cache?: Cache;
  google: GoogleAPI;
}
/**
 * URLATE 자체 설정입니다.
 */
export interface Project {
  /**
   * 서버 구동 모드입니다. production일 때 세션 쿠키에 secure 플래그가 적용됩니다(HTTPS 필요). 설정하지 않으면 production으로 간주합니다.
   */
  mode?: "production" | "test";
  /**
   * 현재 프론트 엔드 서버가 호스트되고 있는 URL입니다. 슬래시로 끝나면 안되는 것에 주의합니다.
   */
  url: string;
  /**
   * 백엔드 서버가 호스트 될 URL입니다. 슬래시로 끝나면 안되는 것에 주의합니다
   */
  api: string;
  /**
   * CDN 서버가 호스트 될 URL입니다. 슬래시로 끝나면 안되는 것에 주의합니다
   */
  cdn: string;
  /**
   * 게임 서버가 호스트 될 URL입니다. 슬래시로 끝나면 안되는 것에 주의합니다
   */
  game: string;
  /**
   * 공지를 가져올 MIRAI(Docusaurus) 사이트의 URL입니다. 슬래시로 끝나면 안되는 것에 주의합니다. 설정하지 않으면 https://mirai.urlate.coupy.dev를 사용합니다.
   */
  mirai?: string;
  /**
   * 백엔드 서버가 열릴 포트입니다.
   */
  port: number;
  /**
   * 백엔드 서버가 바인딩할 주소입니다. 리버스 프록시 뒤에 둔다면 127.0.0.1로 두어 포트가 외부에 직접 노출되지 않게 합니다. 설정하지 않으면 127.0.0.1에만 바인딩합니다.
   */
  host?: string;
  secretKey: string;
  /**
   * 플레이 리플레이 로그를 보관할 일수입니다. 0이면 로그를 남기지 않습니다. 설정하지 않으면 14일간 보관한 뒤 자동 삭제합니다.
   */
  replayLogRetentionDays?: number;
  /**
   * 이 서버 앞에 있는 신뢰할 수 있는 프록시의 홉 수입니다. X-Forwarded-For에서 뒤로부터 이 개수만큼을 건너뛴 주소를 클라이언트 주소로 씁니다. 실제 홉 수와 정확히 맞춰야 합니다. 적으면 레이트리밋이 프록시 주소 하나에 묶이고, 많으면 클라이언트가 헤더로 주소를 위조할 수 있습니다. 설정하지 않으면 CDN + 리버스 프록시 2홉으로 간주합니다.
   */
  trustProxy?: number;
}
/**
 * 데이터베이스 연결 설정입니다.
 */
export interface Database {
  /**
   * MySQL 서버 호스트입니다. 주 데이터베이스로 활용됩니다.
   */
  host: string;
  /**
   * MySQL 저장소 포트입니다.
   */
  port: number;
  /**
   * MySQL 사용자명입니다.
   */
  user: string;
  /**
   * MySQL 사용자의 비밀번호입니다.
   */
  password: string;
  /**
   * MySQL에서 사용할 데이터베이스 이름입니다.
   */
  db: string;
}
/**
 * Redis 연결 설정입니다.
 */
export interface Redis {
  /**
   * Redis 서버 호스트입니다. 세션 저장소에 활용됩니다.
   */
  host: string;
  /**
   * Redis 저장소 포트입니다.
   */
  port: number;
  /**
   * Redis 사용자명입니다.
   */
  username: string;
  /**
   * Redis 사용자의 비밀번호입니다.
   */
  password: string;
}
/**
 * 세션 설정입니다.
 */
export interface Session {
  /**
   * 세션 암호화에 사용할 시크릿 키입니다.
   */
  secret: string;
  /**
   * 세션을 언제나 세션 저장소에 다시 저장할지 여부입니다.
   * 변경된 점이 없더라도 다시 저장할 것이며,
   * 이 값을 true로 설정하는 것은 동시성 문제를 야기할 수도 있습니다.
   * 설정하지 않는다면 true로 설정될 것이나, 미래 버전에서 바뀔 수 있습니다.
   */
  resave: boolean;
  /**
   * 초기화하지 않은 세션일지라도 강제로 저장할지 여부입니다.
   * 초기화하지 않은 세션이라 함은 새로운 세션에 값을 넣지 않았을 때를 말합니다.
   * false로 설정한다면 서버 용량 절약이나 개인정보 보호법 준수, 동시성 문제 해소 등 이점이 많습니다.
   * 설정하지 않는다면 true로 설정될 것이나, 미래 버전에서 바뀔 수 있습니다.
   */
  saveUninitialized: boolean;
  /**
   * 세션 쿠키의 도메인입니다.
   */
  domain: string;
}
/**
 * Redis 캐시 설정입니다. 생략하면 캐시가 켜진 상태로 기본 TTL이 적용됩니다.
 */
export interface Cache {
  /**
   * Redis 읽기 캐시 사용 여부입니다. false로 두면 모든 조회가 MySQL로 직행합니다.
   */
  enabled?: boolean;
  ttl?: CacheTTL;
}
/**
 * 캐시 종류별 유효 시간(초)입니다. 지정하지 않은 항목은 기본값을 사용합니다.
 */
export interface CacheTTL {
  /**
   * 곡 목록(/tracks, /track) 캐시 TTL입니다.
   */
  tracks?: number;
  /**
   * 패턴 정보(/trackInfo) 캐시 TTL입니다.
   */
  trackInfo?: number;
  /**
   * 팀 프로필(/teamProfile) 캐시 TTL입니다.
   */
  teamProfile?: number;
  /**
   * 공지(/notice) 캐시 TTL입니다.
   */
  notice?: number;
  /**
   * 본인 정보(/user) 캐시 TTL입니다. 설정 변경 시 즉시 무효화됩니다.
   */
  user?: number;
  /**
   * 가입 여부(/auth/status) 캐시 TTL입니다. 가입 시 즉시 무효화됩니다.
   */
  authStatus?: number;
  /**
   * 프로필 사진(/profilePic) 캐시 TTL입니다.
   */
  profilePic?: number;
  /**
   * 개인 최고 기록(/record/:filename/:nickname, /bestRecords) 캐시 TTL입니다. 기록 제출 시 즉시 무효화됩니다.
   */
  bestRecord?: number;
  /**
   * 개별 기록(/record/:index) 캐시 TTL입니다.
   */
  record?: number;
  /**
   * 곡별 순위표(/records) 캐시 TTL입니다. 해당 곡 기록 제출 시 즉시 무효화됩니다.
   */
  leaderboard?: number;
  /**
   * 전체 랭킹(/ranking) 캐시 TTL입니다.
   */
  ranking?: number;
  /**
   * 프로필(/profile) 캐시 TTL입니다.
   */
  profile?: number;
  /**
   * 업적 마스터 데이터 캐시 TTL입니다.
   */
  achievements?: number;
}
/**
 * Google API 설정입니다.
 */
export interface GoogleAPI {
  /**
   * Google API 클라이언트 ID입니다.
   */
  clientId: string;
  /**
   * Google API 클라이언트 Secret Key입니다.
   */
  clientSecret: string;
}
